[package]
name = "hungaromet-odp-client"
version = "0.1.1"
authors = ["Zoltan Kovari"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/zkoevaari/hungaromet-odp-client.git"

[dependencies]
